### ISSUE TITLE
Error (use-package): [...]/:catch: Creating pipe: Too many open files

### ISSUE THREAD

**Issue by bbigras** [mjlbach/emacs-pgtk-nativecomp-overlay#7]
I got a lot of those error messages when trying to use `emacsGccPgtk`.

I'm also using the emacs overlay and the emacs-init module.

```
Error (use-package): dap-chrome/:catch: Creating pipe: Too many open files
Error (use-package): dap-firefox/:catch: Creating pipe: Too many open files
Error (use-package): dap-lldb/:catch: Creating pipe: Too many open files
Error (use-package): diff-hl/:catch: Creating pipe: Too many open files
Error (use-package): docker-tramp/:catch: Creating pipe: Too many open files
```

**Comment by mjlbach** [comment]
Im sorry, but I'm not super familiar with the packages you are using; can you provide a minimal nix-shell and steps to reproduce the error?

**Comment by bbigras** [comment]
Sorry for the long delay.

I just updated and tried `emacsGccPgtk` again and I don't seem to have the problem anymore. I'll report if it even happens again.

Thanks.
